sudo: required
dist: trusty

#install google chrome, using addons
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: node_js
node_js:
  - "6"

before_install:
  - npm install -g npm
  - npm install -g greenkeeper-lockfile@1
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.21.3
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn config set spin false
  - yarn config set progress false

install: npm install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - greenkeeper-lockfile-update
  - npm install --quiet -g gulp-cli

script: gulp test:ci

after_script: greenkeeper-lockfile-upload

after_success: gulp coveralls
